name: Build and deploy github pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache container image
      id: cache-container-image
      uses: actions/cache@v4
      with:
        path: docusaurus-plus-develop-image.tar
        key: ${{ runner.os }}-container-image-${{ hashFiles('**/Containerfile.*') }}

    - name: Build develop image
      if: steps.cache-container-image.outputs.cache-hit != 'true'
      working-directory: ./src/container
      run: docker image build . --file ./Containerfile.develop --tag docusaurus-plus-develop-image
    
    - name: Save container image
      if: steps.cache-container-image.outputs.cache-hit != 'true'
      run: docker save docusaurus-plus-develop-image > docusaurus-plus-develop-image.tar
    
    - name: Load container image
      if: steps.cache-container-image.outputs.cache-hit == 'true'
      run: docker load < docusaurus-plus-develop-image.tar

    - name: Build
      working-directory: ./src/
      run: >
        docker run
        --volume "./../content/multiblog/:/workspace/docusaurus-plus/multiblog/"
        --volume "./../content/multidocs/:/workspace/docusaurus-plus/multidocs/"
        --volume "./volume/.vscode/:/workspace/docusaurus-plus/.vscode/"
        --volume "./volume/config/:/workspace/docusaurus-plus/config"
        --volume "./volume/docusaurus.config.ts:/workspace/docusaurus-plus/docusaurus.config.ts"
        --volume "./volume/run.sh:/workspace/docusaurus-plus/run.sh"
        --volume "./volume/src/:/workspace/docusaurus-plus/src/"
        --volume "./volume/static/:/workspace/docusaurus-plus/static/"
        --volume "./../build/:/workspace/docusaurus-plus/build/"
        docusaurus-plus-develop-image
        npm run build

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

  # https://github.com/actions/deploy-pages
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
